#cloud-config
chpasswd:
  list: |
    Administrator:StrongPassword123
  expire: False

# Create Ansible user
users:
  - name: ansible
    password: "AnsiblePassword123"
    groups: "Administrators"
    shell: "powershell.exe"
    lock_passwd: false

# Configure WinRM
winrm:
  enable: true
  listen_address: 0.0.0.0
  port: 5985
  auth:
    basic: true
    kerberos: false
  basic_auth_username: ansible
  basic_auth_password: AnsiblePassword123

# Run commands on first boot
runcmd:
  - net user /add ansible AnsiblePassword123
  - net localgroup administrators ansible /add
  - powershell.exe -Command "Set-ExecutionPolicy Unrestricted -Force"
  - powershell.exe -Command "Install-WindowsFeature -Name Web-Server"
  - powershell.exe -Command "New-NetIPAddress -InterfaceAlias 'Ethernet' -IPAddress '192.168.10.100' -PrefixLength 24 -DefaultGateway '192.168.10.1'"
  - powershell.exe -Command "Set-DnsClientServerAddress -InterfaceAlias 'Ethernet' -ServerAddresses ('8.8.8.8', '8.8.4.4')"
