- name: Provision and configure Windows Server 2019 Domain Controller
  hosts: proxmox
  gather_facts: false
  tasks:
    - name: Clone Windows Server 2019 VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vm_id }}"
        name: dc_clone
        target: "{{ proxmox_node }}"
        full: false
        format: raw
        timeout: 300
      delegate_to: localhost

    - name: Start the cloned VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ proxmox_node }}"
        name: dc_clone
        state: started
      delegate_to: localhost

- name: Configure Domain Controller
  hosts: windows_vm
  gather_facts: false
  tasks:
    - name: Wait for WinRM to be available
      win_wait_for:
        port: 5986
        host: "{{ ansible_host }}"
        timeout: 300

    - name: Ensure the latest PowerShellGet
      win_shell: "Install-Module -Name PowerShellGet -Force -SkipPublisherCheck"
      args:
        executable: powershell.exe

    - name: Install AD-Domain-Services
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes

    - name: Promote to Domain Controller
      win_shell: >
        Install-ADDSForest `
        -DomainName "example.local" `
        -SafeModeAdministratorPassword (ConvertTo-SecureString "P@ssw0rd" -AsPlainText -Force) `
        -InstallDns
      args:
        executable: powershell.exe
