- name: CONFIGURING DOMAIN CONTROLLER
  hosts: windows
  gather_facts: no
  tasks:
    - name: Rename server
      win_hostname:
        name: "DC-Server"
      register: rename
      
    - name: Reboot after rename
      win_reboot:
      when: rename.reboot_required
   
    - name: Installing Active Directory and DNS Server Role
      win_feature:
        name:
          - AD-Domain-Services
          - DNS
        include_management_tools: yes
        include_sub_features: yes
        state: present
      register: result

    - name: Change Administrator password
      win_user:
        name: Administrator
        password: "P@ssw0rd"

    - name: Create domain
      microsoft.ad.domain:
        dns_domain_name: "VetTech.com"
        domain_netbios_name: "VetTech"
        safe_mode_password: "P@ssw0rd"
        reboot: true

    - name: Set internal DNS server 
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
        - '127.0.0.1'

    - name: Allow RDP to specific users
      ansible.windows.win_user_right:
        name: SeRemoteInteractiveLogonRight
        users:
        - Administrators

    - name: Misconfiguration - Add jacktest account (ws2 account)
      microsoft.ad.user:
        name: 'Hans S. Hoyos'
        firstname: Hans
        surname: Hoyos
        password: 'P@ssw0rd'
        state: present
        domain_username: hhoyos
        domain_password: 'P@ssw0rd'
        groups:
          set:
          - Domain Users
          - Remote Desktop Users
